-- Combined schema + seed for D1 dashboard one-shot paste
-- Regenerate seed with: npx tsx scripts/seed.ts (then re-run this if data/tools.ts changed)

-- Initial schema for the AI tools directory.
-- Run with: wrangler d1 migrations apply ai-tools-directory --local
--           wrangler d1 migrations apply ai-tools-directory --remote

CREATE TABLE IF NOT EXISTS categories (
  slug       TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  tagline    TEXT NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tools (
  slug       TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  category   TEXT NOT NULL,
  tagline    TEXT NOT NULL,
  description TEXT NOT NULL,
  pricing    TEXT NOT NULL,
  rating     REAL NOT NULL DEFAULT 0,
  pros       TEXT NOT NULL DEFAULT '[]',
  cons       TEXT NOT NULL DEFAULT '[]',
  website    TEXT NOT NULL,
  featured   INTEGER NOT NULL DEFAULT 0,
  bestFor    TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_tools_category ON tools(category);

CREATE TABLE IF NOT EXISTS reviews (
  slug     TEXT PRIMARY KEY,
  title    TEXT NOT NULL,
  excerpt  TEXT NOT NULL,
  readMins INTEGER NOT NULL DEFAULT 0,
  toolSlug TEXT,
  date     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS comparisons (
  slug  TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  a     TEXT NOT NULL,
  b     TEXT NOT NULL
);

-- seed --
-- Seed data generated from data/tools.ts. Do not edit by hand.
DELETE FROM comparisons;
DELETE FROM reviews;
DELETE FROM tools;
DELETE FROM categories;

INSERT INTO categories (slug,name,tagline,description) VALUES ('copywriting','Copywriting','AI that writes your ads, emails and blogs','AI writing assistants that draft marketing copy, product descriptions, ad variants and long-form content in seconds.');
INSERT INTO categories (slug,name,tagline,description) VALUES ('seo','SEO','Rank higher with AI-guided optimization','Content optimization, keyword research and on-page SEO tools powered by AI to help you outrank competitors.');
INSERT INTO categories (slug,name,tagline,description) VALUES ('ads-creative','Ads & Creative','Generate ad creatives that convert','AI platforms that produce scroll-stopping ad creatives, social graphics and campaign assets at scale.');
INSERT INTO categories (slug,name,tagline,description) VALUES ('social-media','Social Media','Plan, write and schedule social posts','Tools to generate captions, repurpose content and auto-schedule posts across every social channel.');
INSERT INTO categories (slug,name,tagline,description) VALUES ('email-outreach','Email & Outreach','Personalize and automate cold & warm email','AI email assistants that write personalized outreach, coach deliverability and automate follow-ups.');
INSERT INTO categories (slug,name,tagline,description) VALUES ('image-design','Image & Design','Design assets without a designer','AI image generators and design tools for logos, thumbnails, product shots and brand kits.');
INSERT INTO categories (slug,name,tagline,description) VALUES ('video','Video','Produce videos from text or avatars','Turn scripts into branded videos with AI avatars, auto-editing and captioning — no camera needed.');
INSERT INTO categories (slug,name,tagline,description) VALUES ('chatbots','Chatbots','24/7 AI support and lead capture','Conversational AI bots for website support, lead qualification and WhatsApp/Instagram automation.');
INSERT INTO categories (slug,name,tagline,description) VALUES ('productivity','Productivity','Run your business on autopilot','AI meeting notes, task automation and planning tools that give small teams superpowers.');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('jasper','Jasper','copywriting','AI copywriting for marketing teams','Jasper is an AI writing platform built for marketing teams, with brand voice, campaign workflows and 50+ templates for ads, blogs and emails.','From $39/mo',4.6,'["Strong brand-voice controls","Team collaboration","Many templates"]','["Pricier than solo tools","Learning curve for workflows"]','https://www.jasper.ai',1,'Agencies and in-house marketing teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('copy-ai','Copy.ai','copywriting','Go-to-market copy in one click','Copy.ai generates sales, marketing and ops copy and now ships workflow automation for repetitive content tasks.','Free + from $36/mo',4.4,'["Generous free tier","Workflow automation","Multilingual"]','["Long-form needs editing","UI can feel busy"]','https://www.copy.ai',0,'Founders and SDRs');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('writesonic','Writesonic','copywriting','SEO-optimized articles at scale','Writesonic writes fact-checked, SEO-ready articles and landing pages, with Chatsonic for real-time search.','Free + from $16/mo',4.3,'["Good SEO article mode","Affordable","Bulk generation"]','["Tone varies","Credits run out fast"]','https://writesonic.com',0,'Content marketers on a budget');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('rytr','Rytr','copywriting','Affordable AI writing for everyone','Rytr is a lightweight, low-cost writing assistant for short-form copy across 40+ use cases and 30+ languages.','Free + from $9/mo',4.2,'["Cheapest on the list","Simple UI","Fast"]','["Weak long-form","Limited depth"]','https://rytr.me',0,'Solopreneurs and students');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('anyword','Anyword','copywriting','Copy scored by predicted performance','Anyword adds a predictive performance score to every variant so you pick copy that converts before you ship it.','From $39/mo',4.1,'["Performance predictions","A/B variant ideas","Good for ads"]','["Scores are estimates","Niche use case"]','https://anyword.com',0,'Performance and paid-media teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('wordtune','Wordtune','copywriting','Rewrite and refine your writing','Wordtune helps you rewrite, shorten and adjust tone, with a Spices feature to add facts, examples and counterarguments.','Free + from $10/mo',4,'["Great rewriting","Browser extension","Tone control"]','["Not for full drafts","Limited languages"]','https://www.wordtune.com',0,'Non-native English writers');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('grammarlygo','GrammarlyGO','copywriting','AI writing inside your everyday apps','GrammarlyGO brings contextual AI drafting and rewriting to the Grammarly you already use across docs, email and the web.','Free + from $12/mo',4.2,'["Ubiquitous","Tone + clarity","Trusted brand"]','["Less creative","Premium for volume"]','https://www.grammarly.com',0,'Everyday business writing');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('surfer-seo','Surfer SEO','seo','On-page SEO that ranks','Surfer analyzes the top-ranking pages for any keyword and gives you a data-backed content outline and real-time optimization score.','From $69/mo',4.8,'["Excellent content scorer","SERP analyzer","Clear guidance"]','["No keyword research","Can be formulaic"]','https://surferseo.com',1,'Content teams chasing rankings');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('clearscope','Clearscope','seo','Enterprise content optimization','Clearscope is the premium content-grade platform trusted by enterprises for thorough term research and reporting.','From $170/mo',4.5,'["Best-in-class reports","Google Docs integration","Trusted by SEOs"]','["Expensive","No free tier"]','https://www.clearscope.io',0,'Enterprise content ops');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('frase','Frase','seo','Research, write and optimize in one','Frase turns a keyword into a full brief, draft and optimized article, with answering-engine features for AEO.','From $15/mo',4.3,'["Brief + write + optimize","Affordable","Answer engine"]','["UI slower","Support limited"]','https://www.frase.io',0,'Freelance SEO writers');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('neuronwriter','NeuronWriter','seo','Semantic SEO on a budget','NeuronWriter scores content against NLP terms and competitor intent, with a generous credit model for small teams.','From $19/mo',4.2,'["Great value","NLP term suggestions","Plenty of credits"]','["Clunky UI","Reporting basic"]','https://neuronwriter.com',0,'Small agencies');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('se-ranking','SE Ranking','seo','All-in-one SEO toolkit','SE Ranking bundles rank tracking, site audit, keyword research and a content editor with AI writing baked in.','From $49/mo',4.4,'["Full toolkit","Competitive pricing","AI writer"]','["Jack of all trades","Data lag"]','https://seranking.com',0,'Agencies managing many sites');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('alli-ai','Alli AI','seo','Automate technical SEO fixes','Alli AI deploys sitewide SEO optimizations and isolated tests automatically, great for large catalogs and templates.','From $299/mo',3.9,'["Automated fixes","Scales to big sites","A/B testing"]','["Pricey","Risky auto-changes"]','https://www.alli.ai',0,'Ecommerce and enterprise');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('outranking','Outranking','seo','SEO content with strategy','Outranking plans content around clusters and intent, then drafts and optimizes with a focus on ranking speed.','From $29/mo',4,'["Content strategy view","Good optimizer","Concepts feature"]','["Slow generation","Steeper learning"]','https://www.outranking.io',0,'SEO strategists');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('adcreative-ai','AdCreative.ai','ads-creative','Convert-performing ad creatives','AdCreative.ai generates hundreds of ad creatives and scores them by predicted conversion, with direct ad-platform push.','From $29/mo',4.1,'["Fast creative variants","Performance scores","Integrates with ads"]','["Templates feel similar","Credits limited"]','https://www.adcreative.ai',0,'Paid-media buyers');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('predis-ai','Predis.ai','ads-creative','Social creatives & competitor analysis','Predis.ai creates social posts, carousels and videos and analyzes competitors'' social performance for inspiration.','Free + from $29/mo',4,'["Carousel + video","Competitor insights","Easy"]','["Video quality mixed","Branding limits"]','https://predis.ai',0,'Social media managers');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('madgicx','Madgicx','ads-creative','AI growth for Meta & Google ads','Madgicx combines creative generation, audience insights and autonomous bidding optimization for ad accounts.','From $32/mo',4,'["Full ad suite","Autonomous optimization","Creative insights"]','["Overwhelming","Best on Meta"]','https://madgicx.com',0,'DTC brands');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('creatopy','Creatopy','ads-creative','Design and animate ad sets','Creatopy is a design automation tool for producing resize-ready, animated ad sets across formats and platforms.','From $17/mo',3.9,'["Design automation","Animations","Resizing"]','["Not AI-native copy","Credit caps"]','https://www.creatopy.com',0,'In-house design teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('pencil','Pencil','ads-creative','Predict which ads will win','Pencil generates and predicts ad performance using your past creative data to forecast winners before spend.','From $49/mo',3.8,'["Predictive scoring","Creative analytics","Templates"]','["Needs history","Limited free"]','https://pencil.io',0,'Performance creative teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('ocoya','Ocoya','social-media','AI captions + scheduling','Ocoya writes captions and creates graphics, then schedules them across all major social networks from one place.','Free + from $15/mo',4,'["Caption + design + schedule","Many channels","Affordable"]','["Design depth limited","Bulk quirks"]','https://www.ocoya.com',0,'Solopreneurs');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('lately','Lately','social-media','Turn long content into social posts','Lately uses AI to atomize blogs, videos and podcasts into on-brand social posts that already perform well.','From $49/mo',3.9,'["Content repurposing","Performance-based","Brand voice"]','["Higher price","Learning curve"]','https://lately.ai',0,'Content-heavy brands');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('buffer','Buffer','social-media','Simple scheduling + AI assistant','Buffer is the friendly scheduler now with an AI assistant for post ideas, rewrites and optimal timing.','Free + from $6/mo',4.3,'["Easy","Free tier","AI suggestions"]','["Basic analytics","Fewer channels on free"]','https://buffer.com',0,'Small teams and creators');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('metricool','Metricool','social-media','Analytics + scheduling + AI','Metricool schedules posts and unifies analytics across social, web and ads, with AI post generation included.','Free + from $18/mo',4.2,'["Strong analytics","Competitive price","Multi-platform"]','["UI dense","AI basic"]','https://metricool.com',0,'Data-driven social teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('postplanner','Post Planner','social-media','Find & post viral content','Post Planner surfaces trending content in your niche and helps you post it with AI-written commentary.','From $7/mo',3.7,'["Content discovery","Cheap","Quick"]','["Dated UI","Limited AI"]','https://www.postplanner.com',0,'Local businesses');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('smartwriter','Smartwriter','email-outreach','Personalized cold emails at scale','Smartwriter auto-researches prospects and writes hyper-personalized cold emails and LinkedIn messages in bulk.','From $49/mo',4,'["Deep personalization","LinkedIn + email","Bulk"]','["Occasional misfires","Credits cap"]','https://www.smartwriter.ai',0,'B2B lead gen');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('lavender','Lavender','email-outreach','Write emails that get replies','Lavender is an AI email coach that scores your drafts for clarity and reply-likelihood right inside Gmail/Outlook.','Free + from $12/mo',4.3,'["Inbox integration","Real-time coaching","Free tier"]','["Focused on sales","Limit on sends"]','https://www.lavender.ai',0,'Sales reps');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('reply-io','Reply.io','email-outreach','Multichannel sales automation','Reply.io automates email, LinkedIn and calls with AI-generated sequences and a meeting-booking assistant.','From $60/mo',4.1,'["Multichannel","AI sequences","Dialer"]','["Setup time","Pricey for solos"]','https://reply.io',0,'Sales orgs');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('mailchimp','Mailchimp','email-outreach','Email marketing with AI','Mailchimp''s IntelliSense writes subject lines and content, with automation and audience tools for small business.','Free + from $13/mo',4,'["Brand trust","Automations","Free tier"]','["Price creeps up","Templates dated"]','https://mailchimp.com',0,'Small business newsletters');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('instantly','Instantly','email-outreach','Cold email infrastructure','Instantly runs unlimited cold email at scale with AI writing, deliverability warmup and inbox rotation.','From $37/mo',4.2,'["Deliverability focus","Unlimited sending","AI copy"]','["Not for newsletters","Learning curve"]','https://instantly.ai',0,'Agencies doing cold outreach');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('lemlist','Lemlist','email-outreach','Human cold outreach that lands','Lemlist blends personalized email, LinkedIn and calls with AI copy and a strong deliverability reputation.','From $59/mo',4.1,'["Personalization","Deliverability","Multichannel"]','["Premium price","Steeper setup"]','https://www.lemlist.com',0,'Outbound-focused teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('canva','Canva','image-design','Design anything, easily','Canva''s Magic Studio brings AI image generation, resize, edit and brand kits into the design tool millions use daily.','Free + from $13/mo',4.6,'["Ubiquitous","Magic Studio AI","Templates galore"]','["Not pro-grade","Storage caps"]','https://www.canva.com',1,'Everyone');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('designs-ai','Designs.ai','image-design','Logos, videos & brand kits','Designs.ai generates logos, graphics, videos and voiceovers from a single brand brief for quick asset production.','From $29/mo',3.9,'["Full brand kit","Video + voice","Fast"]','["Stock feel","Limited control"]','https://designs.ai',0,'New brands');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('midjourney','Midjourney','image-design','Best-in-class image generation','Midjourney produces the most aesthetically striking AI images, now with web editor and style references.','From $10/mo',4.5,'["Top image quality","Style control","Active community"]','["No free tier","Learning curve"]','https://www.midjourney.com',0,'Creatives and agencies');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('leonardo-ai','Leonardo.Ai','image-design','Game & product asset generation','Leonardo.Ai generates consistent, production-ready assets with fine-tuned models and a robust editing canvas.','Free + from $10/mo',4.3,'["Consistent styles","Free tier","Editing tools"]','["Credits reset","GPU queues"]','https://leonardo.ai',0,'Game and product teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('adobe-firefly','Adobe Firefly','image-design','Commercially safe AI imaging','Firefly powers generative fill and recolor inside Adobe apps, trained on licensed data for commercial use.','Free + from $10/mo',4.2,'["Commercially safe","In Creative Cloud","Generative fill"]','["Needs Adobe sub","Less wild"]','https://www.adobe.com/products/firefly.html',0,'Designers on Adobe');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('looka','Looka','image-design','AI logo & brand identity','Looka generates a full brand identity — logo, palette, fonts and social kits — from a few style choices.','From $20 one-time',3.9,'["Full brand kit","Cheap","Fast"]','["Generic at times","Limited edits"]','https://looka.com',0,'Startups needing a logo');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('khroma','Khroma','image-design','AI color palette generator','Khroma learns the colors you like and generates unlimited palettes and combinations for design systems.','Free',3.7,'["Free","Personalized","Useful"]','["Narrow use","Web only"]','https://www.khroma.co',0,'Designers picking colors');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('heygen','HeyGen','video','AI avatar videos from text','HeyGen turns scripts into polished spokesperson videos with realistic avatars and instant translation to 40+ languages.','Free + from $29/mo',4.7,'["Realistic avatars","Video translation","Easy"]','["Avatar limits","Credits"]','https://www.heygen.com',1,'Marketing & L&D teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('synthesia','Synthesia','video','Enterprise AI video platform','Synthesia is the enterprise standard for avatar videos, with 160+ avatars, templates and security compliance.','From $29/mo',4.5,'["Enterprise-ready","Many avatars","Templates"]','["Higher tiers pricey","Less creative freedom"]','https://www.synthesia.io',0,'Large companies');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('pictory','Pictory','video','Blog & script to video','Pictory auto-summarizes long content into short branded videos with stock footage, captions and AI voices.','From $19/mo',4.1,'["Content repurposing","Captions","Stock library"]','["Stock-heavy","Editing limits"]','https://pictory.ai',0,'Content marketers');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('descript','Descript','video','Edit video by editing text','Descript lets you edit podcasts and videos like a doc, with overdub, filler-word removal and studio sound.','Free + from $12/mo',4.4,'["Text-based editing","Overdub","Great audio tools"]','["Render times","Learning curve"]','https://www.descript.com',0,'Podcasters & editors');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('runway','Runway','video','Generative video & magic tools','Runway offers Gen-2 video generation plus a deep suite of AI editing effects for filmmakers and creators.','Free + from $12/mo',4.3,'["Cutting-edge gen","Many effects","Creative"]','["Credits burn","Can be unpredictable"]','https://runwayml.com',0,'Creative studios');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('veed','VEED','video','Simple online video editor','VEED is a browser editor with AI subtitles, cleanup and avatar tools aimed at quick social and training videos.','Free + from $18/mo',4,'["Easy editor","Auto subtitles","Avatar beta"]','["Watermark on free","Export limits"]','https://www.veed.io',0,'Social video creators');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('luma-dream-machine','Luma Dream Machine','video','Realistic AI video from prompts','Luma''s Dream Machine generates highly realistic motion and camera moves from text or images in seconds.','Free + from $10/mo',4.2,'["Photoreal motion","Fast","Image-to-video"]','["Short clips","Credits"]','https://lumalabs.ai/dream-machine',0,'Filmmakers experimenting');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('intercom-fin','Intercom Fin','chatbots','AI support that resolves tickets','Fin is Intercom''s resolution bot that answers from your help content and resolves up to half of support volume.','From $0.99/resolution',4.3,'["High resolution rate","Trusted platform","Multilingual"]','["Pay per resolution","Setup needed"]','https://www.intercom.com',0,'Support teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('tidio','Tidio','chatbots','Live chat + AI bots for SMBs','Tidio combines live chat with Lyro, an AI agent that handles common questions and captures leads on your site.','Free + from $29/mo',4.1,'["Easy setup","Lyro AI","Affordable"]','["Fewer integrations","Bot limits"]','https://www.tidio.com',0,'Small business websites');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('chatfuel','Chatfuel','chatbots','Messenger & Instagram bots','Chatfuel builds no-code bots for Meta channels with AI replies, comment automation and lead capture.','From $15/mo',3.9,'["Meta-focused","No-code","Comment automation"]','["Meta-centric","Template limits"]','https://chatfuel.com',0,'Ecommerce on social');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('manychat','Manychat','chatbots','Growth tools for messaging','Manychat automates Instagram, WhatsApp and Messenger with AI flows for comments, DMs and broadcasts.','Free + from $15/mo',4,'["Strong IG/WA","Free tier","Flow builder"]','["Meta policy risk","Complex flows"]','https://manychat.com',0,'Influencers & DTC');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('botpress','Botpress','chatbots','Developer-grade AI agents','Botpress is an open, LLM-powered bot platform with a visual builder and deep integrations for technical teams.','Free + from $0.02/message',4.1,'["Powerful","Open","Great docs"]','["Dev-oriented","Cost scales"]','https://botpress.com',0,'Engineering teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('drift','Drift','chatbots','Conversational marketing','Drift uses AI to qualify site visitors and book meetings with sales in real time, focused on B2B pipeline.','Custom',3.8,'["Meeting booking","B2B focus","Routing"]','["Expensive","Sales-led buying"]','https://www.drift.com',0,'B2B revenue teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('notion-ai','Notion AI','productivity','AI inside your workspace','Notion AI writes, summarizes and answers questions across your docs and databases, all in one workspace.','From $10/mo',4.3,'["Context-aware","In workspace","Q&A over docs"]','["Needs Notion","Credit limits"]','https://www.notion.so/product/ai',0,'Teams on Notion');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('motion','Motion','productivity','AI calendar & task automation','Motion auto-schedules your tasks and meetings into the optimal slots, defending focus time automatically.','From $19/mo',4,'["Smart scheduling","Time blocking","Cross-device"]','["Pushy auto-sort","Price"]','https://www.usemotion.com',0,'Busy founders');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('reclaim','Reclaim','productivity','Defend your time automatically','Reclaim auto-schedules habits, tasks and meetings around your priorities, and adapts when plans change.','Free + from $8/mo',4.1,'["Adaptive","Habits","Google Calendar"]','["Google-only","Setup time"]','https://reclaim.ai',0,'Calendar-heavy teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('taskade','Taskade','productivity','AI agents for your projects','Taskade blends docs, tasks and customizable AI agents that plan and execute work inside your workspace.','Free + from $8/mo',4,'["AI agents","All-in-one","Affordable"]','["Feature sprawl","UI busy"]','https://www.taskade.com',0,'Small teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('fireflies','Fireflies.ai','productivity','Meeting notes on autopilot','Fireflies records, transcribes and summarizes meetings across Zoom, Meet and Teams, with searchable insights.','Free + from $10/mo',4.2,'["Accurate transcripts","Search","Integrations"]','["Storage caps","Bot joins calls"]','https://fireflies.ai',0,'Meeting-heavy teams');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('otter','Otter.ai','productivity','Live notes & summaries','Otter provides real-time transcription and AI meeting summaries with action items pushed to your tools.','Free + from $8/mo',4,'["Live transcription","Summaries","Mobile"]','["Free minute cap","Accuracy varies"]','https://otter.ai',0,'Individuals in meetings');
INSERT INTO tools (slug,name,category,tagline,description,pricing,rating,pros,cons,website,featured,bestFor) VALUES ('mem','Mem','productivity','Self-organizing notes','Mem is an AI note app that auto-links and resurfaces related notes so knowledge stays connected without folders.','Free + from $8/mo',3.8,'["Auto-organized","Fast capture","Resurfacing"]','["Niche","Sync limits"]','https://mem.ai',0,'Knowledge workers');
INSERT INTO reviews (slug,title,excerpt,readMins,toolSlug,date) VALUES ('best-ai-seo-tools-2026','Best AI SEO tools in 2026 (tested & ranked)','We put 9 AI SEO platforms through real content briefs. Here''s which actually move rankings — and which just look good in demos.',5,'surfer-seo','2026-08-01');
INSERT INTO reviews (slug,title,excerpt,readMins,toolSlug,date) VALUES ('free-jasper-alternatives','6 free Jasper alternatives worth trying','Jasper is great but not cheap. These six AI writers deliver real value on a free or near-free plan.',6,'jasper','2026-07-28');
INSERT INTO reviews (slug,title,excerpt,readMins,toolSlug,date) VALUES ('heygen-vs-synthesia','HeyGen vs Synthesia: which avatar video tool wins?','Both turn scripts into spokesperson videos. We compare avatars, languages, pricing and ease of use head-to-head.',7,'heygen','2026-07-22');
INSERT INTO reviews (slug,title,excerpt,readMins,toolSlug,date) VALUES ('ai-tools-for-small-business','12 AI tools every small business should pilot','A practical starter stack — support, content, social and admin — that a team of one can run on a shoestring.',8,NULL,'2026-07-15');
INSERT INTO comparisons (slug,title,a,b) VALUES ('surfer-seo-vs-clearscope','Surfer SEO vs Clearscope','surfer-seo','clearscope');
INSERT INTO comparisons (slug,title,a,b) VALUES ('jasper-vs-copy-ai','Jasper vs Copy.ai','jasper','copy-ai');
INSERT INTO comparisons (slug,title,a,b) VALUES ('heygen-vs-synthesia','HeyGen vs Synthesia','heygen','synthesia');
INSERT INTO comparisons (slug,title,a,b) VALUES ('midjourney-vs-leonardo','Midjourney vs Leonardo.Ai','midjourney','leonardo-ai');
INSERT INTO comparisons (slug,title,a,b) VALUES ('instantly-vs-lemlist','Instantly vs Lemlist','instantly','lemlist');
